import { PanelBody } from './PanelBody';
import { PanelCallout } from './PanelCallout';
import { PanelCheckboxItem } from './PanelCheckboxItem';
import { PanelContent } from './PanelContent';
import { PanelDataTable } from './PanelDataTable';
import { PanelEmptyState } from './PanelEmptyState';
import { PanelField, PanelFieldList } from './PanelField';
import {
  PanelFooter,
  PanelFooterEnd,
  PanelFooterLink,
  PanelFooterStart,
  PanelLink,
} from './PanelFooter';
import { PanelGroup, PanelGroupContent } from './PanelGroup';
import {
  PanelDescription,
  PanelHeader,
  PanelHeaderAction,
  PanelHeaderText,
  PanelLabelRow,
  PanelTitle,
} from './PanelHeader';
import { PanelInfoTip } from './PanelInfoTip';
import {
  PanelNavItem,
  PanelNavList,
  PanelSplit,
  PanelStat,
  PanelStats,
  PanelToolbar,
  PanelToolbarEnd,
  PanelToolbarStart,
  PanelView,
} from './PanelNav';
import { PanelQueryState } from './PanelQueryState';
import { PanelFixedRoot, PanelGrid, PanelMain, PanelRoot } from './PanelRoot';
import { PanelRow, PanelRowContent, PanelRowHeader } from './PanelRow';
import { PanelDividerLabel, PanelRowGroup } from './PanelRowGroup';
import {
  PanelRowAction,
  PanelRowBadge,
  PanelRowDescription,
  PanelRowIcon,
  PanelRowSwitch,
  PanelRowText,
  PanelRowTitle,
} from './PanelRowParts';
import {
  PanelSection,
  PanelSectionDescription,
  PanelSectionTitle,
} from './PanelSection';
import {
  PanelChartSkeleton,
  PanelGaugeSkeleton,
  PanelHeaderSkeleton,
  PanelRowSkeleton,
} from './PanelSkeleton';
import {
  PanelTable,
  PanelTableBody,
  PanelTableCell,
  PanelTableHead,
  PanelTableHeader,
  PanelTableRow,
} from './PanelTable';

const Panel = Object.assign(
  () => {
    throw new Error('Panel is not a component. Render Panel.Root instead.');
  },
  {
    Root: PanelRoot,
    FixedRoot: PanelFixedRoot,
    Grid: PanelGrid,
    Main: PanelMain,
    Body: PanelBody,
    Header: PanelHeader,
    Title: PanelTitle,
    Description: PanelDescription,
    HeaderText: PanelHeaderText,
    HeaderAction: PanelHeaderAction,
    LabelRow: PanelLabelRow,
    InfoTip: PanelInfoTip,
    Content: PanelContent,
    EmptyState: PanelEmptyState,
    QueryState: PanelQueryState,
    Footer: PanelFooter,
    FooterStart: PanelFooterStart,
    FooterEnd: PanelFooterEnd,
    FooterLink: PanelFooterLink,
    Link: PanelLink,
    Group: PanelGroup,
    GroupContent: PanelGroupContent,
    Row: PanelRow,
    RowHeader: PanelRowHeader,
    RowSwitch: PanelRowSwitch,
    RowIcon: PanelRowIcon,
    RowText: PanelRowText,
    RowTitle: PanelRowTitle,
    RowDescription: PanelRowDescription,
    RowBadge: PanelRowBadge,
    RowAction: PanelRowAction,
    RowContent: PanelRowContent,
    RowGroup: PanelRowGroup,
    DividerLabel: PanelDividerLabel,
    Callout: PanelCallout,
    Section: PanelSection,
    SectionTitle: PanelSectionTitle,
    SectionDescription: PanelSectionDescription,
    CheckboxItem: PanelCheckboxItem,
    Stats: PanelStats,
    Stat: PanelStat,
    Toolbar: PanelToolbar,
    ToolbarStart: PanelToolbarStart,
    ToolbarEnd: PanelToolbarEnd,
    Split: PanelSplit,
    NavList: PanelNavList,
    NavItem: PanelNavItem,
    View: PanelView,
    RowSkeleton: PanelRowSkeleton,
    HeaderSkeleton: PanelHeaderSkeleton,
    ChartSkeleton: PanelChartSkeleton,
    GaugeSkeleton: PanelGaugeSkeleton,
    FieldList: PanelFieldList,
    Field: PanelField,
    Table: PanelTable,
    DataTable: PanelDataTable,
    TableHeader: PanelTableHeader,
    TableHead: PanelTableHead,
    TableBody: PanelTableBody,
    TableRow: PanelTableRow,
    TableCell: PanelTableCell,
  },
);

export { Panel };
export {
  PanelStats,
  PanelStat,
  PanelToolbar,
  PanelToolbarStart,
  PanelToolbarEnd,
  PanelSplit,
  PanelNavList,
  PanelNavItem,
  PanelView,
};
export {
  PanelRoot,
  PanelFixedRoot,
  PanelGrid,
  PanelMain,
  PanelBody,
  PanelHeader,
  PanelTitle,
  PanelDescription,
  PanelHeaderText,
  PanelHeaderAction,
  PanelLabelRow,
  PanelInfoTip,
  PanelContent,
  PanelEmptyState,
  PanelQueryState,
  PanelFooter,
  PanelFooterStart,
  PanelFooterEnd,
  PanelFooterLink,
  PanelLink,
  PanelGroup,
  PanelGroupContent,
  PanelRow,
  PanelRowHeader,
  PanelRowSwitch,
  PanelRowIcon,
  PanelRowText,
  PanelRowTitle,
  PanelRowDescription,
  PanelRowBadge,
  PanelRowAction,
  PanelRowContent,
  PanelRowGroup,
  PanelDividerLabel,
  PanelCallout,
  PanelSection,
  PanelSectionTitle,
  PanelSectionDescription,
  PanelCheckboxItem,
  PanelRowSkeleton,
  PanelHeaderSkeleton,
  PanelChartSkeleton,
  PanelGaugeSkeleton,
  PanelFieldList,
  PanelField,
  PanelTable,
  PanelDataTable,
  PanelTableHeader,
  PanelTableHead,
  PanelTableBody,
  PanelTableRow,
  PanelTableCell,
};
export type {
  PanelRootProps,
  PanelGridProps,
  PanelMainProps,
  PanelBodyProps,
  PanelHeaderProps,
  PanelTitleProps,
  PanelDescriptionProps,
  PanelHeaderTextProps,
  PanelHeaderActionProps,
  PanelLabelRowProps,
  PanelInfoTipProps,
  PanelContentProps,
  PanelEmptyStateProps,
  PanelQueryStateProps,
  PanelFooterProps,
  PanelFooterStartProps,
  PanelFooterEndProps,
  PanelFooterLinkProps,
  PanelLinkProps,
  PanelGroupProps,
  PanelGroupContentProps,
  PanelRowProps,
  PanelRowHeaderProps,
  PanelRowSwitchProps,
  PanelRowIconProps,
  PanelRowTextProps,
  PanelRowTitleProps,
  PanelRowDescriptionProps,
  PanelRowBadgeProps,
  PanelRowActionProps,
  PanelRowContentProps,
  PanelRowGroupProps,
  PanelDividerLabelProps,
  PanelCalloutProps,
  PanelSectionProps,
  PanelSectionTitleProps,
  PanelSectionDescriptionProps,
  PanelCheckboxItemProps,
  PanelRowSkeletonProps,
  PanelHeaderSkeletonProps,
  PanelChartSkeletonProps,
  PanelGaugeSkeletonProps,
  PanelTableProps,
  PanelDataTableProps,
  PanelFieldListProps,
  PanelFieldProps,
  PanelDataTableColumn,
  PanelDataTableSort,
  PanelTableHeaderProps,
  PanelTableHeadProps,
  PanelTableBodyProps,
  PanelTableRowProps,
  PanelTableCellProps,
} from './types';
